### ISSUE TITLE
utils.js:50 chunk not available for synchronous require yet: 

### ISSUE THREAD

**Issue by manish4781** [faceyspacey/react-universal-component#140]
i am using this boilerplate https://github.com/rherwig/template-react-16-ssr
getting the following error **utils.js:50 chunk not available for synchronous require yet:** for my multiple modules, could you please describe what could be the issue and how can i control my chunks size 

Sample error

```
utils.js:50 chunk not available for synchronous require yet: ./src/shared/components/AhHeader.js: Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.

(Source code omitted for this binary file)
    at handleParseError (/mnt/www/artifacts/x/5820/node_modules/webpack/lib/NormalModule.js:432:19)
    at doBuild.err (/mnt/www/artifacts/x.dev/5820/node_modules/webpack/lib/NormalModule.js:466:5)
    at runLoaders (/mnt/www/artifacts/x.dev/5820/node_modules/webpack/lib/NormalModule.js:327:12)
    at /mnt/www/artifacts/x.dev/5820/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/mnt/www/artifacts/x.dev/5820/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/mnt/www/artifacts/x.dev/5820/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/mnt/www/artifacts/x.dev/5820/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/mnt/www/artifacts/x.dev/5820/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /mnt/www/artifacts/x.dev/5820/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3) Error: Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

**Comment by manish4781** [comment]
It turned out, i had some webpack config missing to load some font files, which was causing this issue.
