### ISSUE TITLE
chunk not available for synchronous require yet

### ISSUE THREAD

**Issue by cihati** [faceyspacey/react-universal-component#167]
First of all, thanks for the great libraries @faceyspacey @ScriptedAlchemy  =)

I've seen #104, #128, #114 but couldn't find a solution.

```
chunk not available for synchronous require yet: ./app/containers/Item.js: Cannot read property 'bool' of undefined TypeError: Cannot read property 'bool' of undefined
    at eval (webpack-internal:///./app/components/ViewItem/RequestToRent/Index.js:525:64)
    at Object../app/components/ViewItem/RequestToRent/Index.js (http://localhost:4000/js/client.37b85af83d8ea5aec21f.js:310:1)
    at __webpack_require__ (http://localhost:4000/js/client.41d949dd25ebd2c9340d.js:84:30)
    at eval (webpack-internal:///./app/components/ViewItem/Index.js:23:82)
    at Object../app/components/ViewItem/Index.js (http://localhost:4000/js/client.37b85af83d8ea5aec21f.js:129:1)
    at __webpack_require__ (http://localhost:4000/js/client.41d949dd25ebd2c9340d.js:84:30)
    at eval (webpack-internal:///./app/containers/Item.js:24:88)
    at Module../app/containers/Item.js (http://localhost:4000/js/client.37b85af83d8ea5aec21f.js:401:1)
    at __webpack_require__ (http://localhost:4000/js/client.41d949dd25ebd2c9340d.js:84:30)
    at requireById (webpack-internal:///./node_modules/react-universal-component/dist/requireById/index.js:14:10)
```

react 16.4.0
webpack-flush-chunks 2.0.3
react-universal-component 3.0.3
webpack 4.23.1

no hot module reloading.

any ideas how I can solve this? I run into this as I'm trying to migrate from react 15.4.2 to 16.4.0

**Comment by cihati** [comment]
To close the loop: in a file we were importing prop-types from React, rather than from its own package (as it's a necessity now in react 16)

**Comment by ScriptedAlchemy** [comment]
Glad I could help! Have a good day!
